#!/usr/bin/env bash

# -------------------------------------------------------------------------
# Bootstrap script to setup the system from scratch
# Author: Luca <vipex@vipexsoft.com>
# Version: 0.1
# -------------------------------------------------------------------------

cd "$(dirname "$0")" || exit 1
DOT_ROOT=$(pwd -P)
set -e

log_i() { echo -e "\033[0;34mℹ️ $1\033[0m"; } # Blue
log_o() { echo -e "\033[0;32m✅ $1\033[0m"; } # Green
log_w() { echo -e "\033[0;33m⚠️ $1\033[0m"; } # Yellow
log_e() { echo -e "\033[0;31m❌ $1\033[0m"; } # Red
OS=$(uname -s)

# Get the OS type
case "${OS}" in
Darwin)
  source macos/bootstrap
  ;;
Linux)
  source linux/bootstrap
  ;;
*)
  log_e "Unsupported operating system $(uname -s)."
  exit 1
  ;;
esac

# Uses stow to manage dotfiles
if ! command -v stow &> /dev/null; then
  echo "stow could not be found, please install it first."
  exit 1
fi

# implement stow configuration
DOT_STOW_SOURCE=${DOT_STOW_SOURCE:-"${DOT_ROOT}/dots"}
DOT_STOW_TARGET=${DOT_STOW_TARGET:-"${HOME}"}
if [ -d "${DOT_STOW_SOURCE}" ]; then
  log_i "Configuring dotfiles with stow..."
  stow --dir="${DOT_STOW_SOURCE}" --target="${DOT_STOW_TARGET}"
  log_o "Dotfiles configured."
else
  log_e "Dotfiles directory not found at ${DOT_STOW_SOURCE}"
fi

log_i "Bootstrap process completed."
