#!/usr/bin/env bash

# -------------------------------------------------------------------------
# Bootstrap script to setup the system from scratch
# Author: Luca <vipex@vipexsoft.com>
# Version: 0.1
# -------------------------------------------------------------------------

cd "$(dirname "$0")" || exit 1
DOT_ROOT=$(pwd -P)
set -e

log_i() { echo -e "\033[0;34mℹ️\t$1\033[0m"; } # Blue
log_o() { echo -e "\033[0;32m✅\t$1\033[0m"; } # Green
log_w() { echo -e "\033[0;33m⚠️\t$1\033[0m"; } # Yellow
log_e() { echo -e "\033[0;31m❌\t$1\033[0m"; } # Red
OS=$(uname -s)

# Get the OS type
case "${OS}" in
Darwin)
  source macos/bootstrap
  ;;
Linux)
  source linux/bootstrap
  ;;
*)
  log_e "Unsupported operating system $(uname -s)."
  exit 1
  ;;
esac

# Uses stow to manage dotfiles
if ! command -v stow &> /dev/null; then
  echo "stow could not be found, please install it first."
  exit 1
fi

log_i "Setting up dotfiles with GNU Stow..."
DOT_STOW_SOURCE=${DOT_STOW_SOURCE:-"${DOT_ROOT}/dots"}
DOT_STOW_TARGET=${DOT_STOW_TARGET:-"${HOME}"}
if [ -d "${DOT_STOW_SOURCE}" ] && [ -d "${DOT_STOW_TARGET}" ]; then
  log_i "Configuring dotfiles with stow..."
  cd "${DOT_STOW_SOURCE}" || exit 1
  stow --target="${DOT_STOW_TARGET}" .
  cd "${DOT_ROOT}" || exit 1
  log_o "Dotfiles configured."
else
  log_e "Dotfiles directory not found at ${DOT_STOW_SOURCE}"
  exit 1
fi

# Install oh-my-zsh if not already installed
ZSH="${ZSH:-"${HOME}/.omz"}"
if [ -z "${ZSH}" ] || [ ! -d "${ZSH}" ]; then
  log_i "Installing Oh My Zsh..."
  sh -c "$(curl -fsSL https://install.ohmyz.sh)" "" --unattended --keep-zshrc
  log_o "Oh My Zsh installed."
else
  log_o "Oh My Zsh already installed."
fi

# Install starship prompt if not already installed
if ! command -v starship &> /dev/null; then
  log_i "Installing Starship prompt..."
  curl -sS https://starship.rs/install.sh | sh -s -- --yes
  log_o "Starship prompt installed."
else
  log_o "Starship prompt already installed."
fi

log_i "Bootstrap process completed."
