#!/usr/bin/env bash

# -------------------------------------------------------------------------
# Bootstrap script to setup the system from scratch
# Author: Luca <vipex@vipexsoft.com>
# Version: 0.1
# -------------------------------------------------------------------------

cd "$(dirname "$0")" || exit 1
export DOT_ROOT=$(pwd -P)
set -e

log_i() { echo -e "\033[0;34mℹ️\t$1\033[0m"; } # Blue
log_o() { echo -e "\033[0;32m✅\t$1\033[0m"; } # Green
log_w() { echo -e "\033[0;33m⚠️\t$1\033[0m"; } # Yellow
log_e() { echo -e "\033[0;31m❌\t$1\033[0m"; } # Red
OS=$(uname -s)

# Specific OS setup
case "${OS}" in
Darwin)
  source macos/bootstrap
  ;;
Linux)
  source linux/bootstrap
  ;;
*)
  log_e "Unsupported operating system $(uname -s)."
  exit 1
  ;;
esac

# Setup dotfiles using stow-helper
source stow-helper install

# Install oh-my-zsh if not already installed
ZSH="${ZSH:-"${HOME}/.omz"}"
if [ -z "${ZSH}" ] || [ ! -d "${ZSH}" ]; then
  log_i "Installing Oh My Zsh..."
  sh -c "$(curl -fsSL https://install.ohmyz.sh)" "" --unattended --keep-zshrc
  log_o "Oh My Zsh installed."
else
  log_o "Oh My Zsh already installed."
fi

# Install starship prompt if not already installed
if ! command -v starship &> /dev/null; then
  log_i "Installing Starship prompt..."
  curl -sS https://starship.rs/install.sh | sh -s -- --yes > /dev/null
  log_o "Starship prompt installed."
else
  log_o "Starship prompt already installed."
fi

# Install nvm if not already installed
export NVM_DIR="${NVM:-"${HOME}/.nvm"}"
if [ ! -d "${NVM_DIR}" ]; then
  log_i "Installing NVM (Node Version Manager)..."
  # get latest nvm version from github api
  VERSION=$(curl -s "https://api.github.com/repos/nvm-sh/nvm/releases/latest"| grep tag_name | cut -d '"' -f 4)
  # Install skipping profile modification
  PROFILE=/dev/null curl -o- "https://raw.githubusercontent.com/nvm-sh/nvm/${VERSION}/install.sh" | bash
  log_o "NVM installed."
else
  log_o "NVM already installed."
fi

# Install node LTS with latest npm and set as default
# Install pnpm via corepack
if [ -s "${NVM_DIR}/nvm.sh" ]; then
  \. "${NVM_DIR}/nvm.sh"
  nvm install --lts --latest-npm
  nvm use --lts
  nvm alias default 'lts/*'
  corepack enable
  corepack prepare pnpm@latest --activate

  # Verify installations
  log_i "Installed Node lts version: $(node -v)"
  log_i "Installed npm version: $(npm -v)"
  log_i "Installed pnpm version: $(pnpm -v)"
fi

log_i "Bootstrap process completed."
