# Placed in:
# ${HOME}/Library/Application Support/JetBrains/PhpStorm2025.2
# custom PhpStorm properties (expand/override 'bin/idea.properties')

# Custom paths for config, plugins, system, and log directories
idea.config.path=${user.home}/.config/phpstorm
idea.plugins.path=${user.home}/.config/phpstorm/plugins
idea.system.path=${user.home}/.cache/phpstorm
idea.log.path=${user.home}/.cache/phpstorm/log

# macOS-specific system properties
com.apple.mrj.application.live-resize=false
apple.awt.fileDialogForDirectories=true
apple.awt.graphics.UseQuartz=true
apple.awt.fullscreencapturealldisplays=false
ide.mac.show.native.help=true # false
