#!/usr/bin/env bash

# -------------------------------------------------------------------------
# Bootstrap script to setup MacOS
# Author: Luca <vipex@vipexsoft.com>
# Version: 0.1
# -------------------------------------------------------------------------

# macOS specific setup
log_i "Setting up for macOS..."

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

## Xcode Command Line Tools
if ! xcode-select -p &>/dev/null; then
  log_i "Installing Xcode Command Line Tools..."
  xcode-select --install
  # Pause the script until the user finishes the installation
  log_w "Please install the Xcode Command Line Tools from the pop-up window and then press Enter to continue."
  read -r
else
  log_o "Xcode Command Line Tools already installed."
fi

## Homebrew
if ! command -v brew &>/dev/null; then
  log_i "Installing Homebrew..."
  NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  eval "$(/opt/homebrew/bin/brew shellenv)"
  log_o "Homebrew installed."
else
  log_o "Homebrew already installed."
fi

### Install dependencies via Homebrew
BREWFILE=${BREWFILE:-"macos/Brewfile"}
if [ -f "${BREWFILE}" ]; then
  log_i "Installing packages via Homebrew..."
  brew bundle --file="${BREWFILE}"
  log_o "...packages installation completed."
else
  log_w "Brewfile not found at ${BREWFILE}"
fi

## Mas-cli
MASFILE=${MASFILE:-"./macos/Masfile"}
if ! command -v mas &>/dev/null; then
  log_w "mas-cli not installed, skipping App Store apps installation."
else
  if [ -f "${MASFILE}" ]; then
    log_i "Installing Mac App Store apps via mas-cli..."
    xargs mas install < "${MASFILE}"
    log_o "...Mac App Store apps installation completed."
  else
    log_w "Masfile not found at ${MASFILE}"
  fi
fi

## Load LaunchAgents
DOT_LAUNCH_AGENTS=${DOT_LAUNCH_AGENTS:-"macos/LaunchAgents/"}
if [ -d "${DOT_LAUNCH_AGENTS}" ]; then
  log_i "Loading LaunchAgents..."
  mkdir -p "${HOME}/Library/LaunchAgents"
  for agent in "${DOT_LAUNCH_AGENTS}"*.plist; do
    if [ -f "${agent}" ]; then
      # Link file to ~/Library/LaunchAgents
      ln -sf "$(pwd -P)/${agent}" "${HOME}/Library/LaunchAgents/$(basename "${agent}")"
      # check if the LaunchAgent is already loaded
      if launchctl print gui/"$(id -u)"/"$(basename "${agent}")" &>/dev/null; then
        # Unload the LaunchAgent first
        launchctl bootout gui/"$(id -u)" "${HOME}/Library/LaunchAgents/$(basename "${agent}")" || \
          log_w "Failed to unload existing LaunchAgent $(basename "${agent}")."
      fi
      # Load the LaunchAgent with launchctl bootstrap
      launchctl bootstrap gui/"$(id -u)" "${HOME}/Library/LaunchAgents/$(basename "${agent}")" || \
        log_w "LaunchAgent $(basename "${agent}") is already loaded."
    fi
  done
  log_o "LaunchAgents loaded."
else
  log_w "LaunchAgents directory not found at ${DOT_LAUNCH_AGENTS}"
fi

## macOS specific configurations (defaults)
# TODO: Uncomment the following lines when macos/defaults is ready
if [ -f "./macos/defaults" ]; then
  log_w "Macos defaults still not finished, skipping..."
  #source ./macos/defaults
else
  log_w "macos/defaults script not found, skipping macOS system settings."
fi
